name: activity_log
description: Log app activity for display in app with a ListView.
version: 0.1.1
homepage: ''

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
